### ISSUE TITLE
配置远程mysql服务器之后，执行python manage.py migrate 异常了

### ISSUE THREAD

**Issue by micele00l** [JoyMobileDevelopmentTeam/Joy_QA_Platform#1]
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, django_celery_results, djcelery, guardian, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial...Traceback (most recent call last):
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/Users/micele/.local/share/virtualenvs/Joy_QA_Platform-AYD7Ymz8/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1215, 'Cannot add foreign key constraint')

**Comment by bzc128** [comment]
注意模块迁移的顺序。有些表建立需要外键。

**Comment by micele00l** [comment]
> 注意模块迁移的顺序。有些表建立需要外键。

请问这个顺序应该如何调整？
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, django_celery_results, djcelery, guardian, sessions
Running pre-migrate handlers for application admin
Running pre-migrate handlers for application auth
Running pre-migrate handlers for application contenttypes
Running pre-migrate handlers for application sessions
Running pre-migrate handlers for application django_celery_results
Running pre-migrate handlers for application django_celery_beat
Running pre-migrate handlers for application frame
Running pre-migrate handlers for application ApiManager
Running pre-migrate handlers for application djcelery
Running pre-migrate handlers for application guardian
Running migrations:
  Applying admin.0001_initial...Traceback (most recent call last):

**Comment by bzc128** [comment]
请问，你是如何找到我的联系方式的？



在 2019-03-15 11:34:02，"micele00l" <notifications@github.com> 写道：


注意模块迁移的顺序。有些表建立需要外键。

请问这个顺序应该如何调整？
Operations to perform:
Apply all migrations: admin, auth, contenttypes, django_celery_beat, django_celery_results, djcelery, guardian, sessions
Running pre-migrate handlers for application admin
Running pre-migrate handlers for application auth
Running pre-migrate handlers for application contenttypes
Running pre-migrate handlers for application sessions
Running pre-migrate handlers for application django_celery_results
Running pre-migrate handlers for application django_celery_beat
Running pre-migrate handlers for application frame
Running pre-migrate handlers for application ApiManager
Running pre-migrate handlers for application djcelery
Running pre-migrate handlers for application guardian
Running migrations:
Applying admin.0001_initial...Traceback (most recent call last):

**Comment by bzc128** [comment]
python manage.py makemigrations frame
  python manage.py migrate frame
   python manage.py makemigrations ApiManager
  python manage.py migrate ApiManager
   python manage.py makemigrations
  python manage.py migrate

**Comment by micele00l** [comment]
> python manage.py makemigrations frame
> python manage.py migrate frame
> python manage.py makemigrations ApiManager
> python manage.py migrate ApiManager
> python manage.py makemigrations
> python manage.py migrate

感谢，已经解决！

**Comment by bzc128** [comment]
> > python manage.py makemigrations frame 
> > python manage.py migrate frame 
> > python manage.py makemigrations ApiManager 
> > python manage.py migrate ApiManager 
> > python manage.py makemigrations 
> > python manage.py migrate
> 
> 感谢，已经解决！

麻烦帮我看个问题，点击模块新增，点击项目列表无法显示已有项目，模块列表是也会报同样的错误
![image](https://user-images.githubusercontent.com/37548003/54653573-21251780-4af6-11e9-9520-966156a1211e.png)
不知道你有遇到这个吗
