### ISSUE TITLE
点击项目列表无法显示已有项目，后台报错guardian.exceptions.WrongAppError: Cannot determine content type

### ISSUE THREAD

**Issue by bzc128** [JoyMobileDevelopmentTeam/Joy_QA_Platform#2]
![image](https://user-images.githubusercontent.com/37548003/54353635-7f35a300-468f-11e9-9d3a-ad799c4e36c8.png)
点击模块新增，模块列表是也会报同样的错误

**Comment by micele00l** [comment]
> ![image](https://user-images.githubusercontent.com/37548003/54353635-7f35a300-468f-11e9-9d3a-ad799c4e36c8.png)
> 点击模块新增，模块列表是也会报同样的错误

大佬你这个报错解决了吗？

**Comment by bzc128** [comment]
暂时没有，你解决了告诉我下
